//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace VS2010_TuitionPayment.Authentication {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationSoap", Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponse))]
    public partial class Authentication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAuthorizationTokenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Authentication() {
            this.Url = global::VS2010_TuitionPayment.Properties.Settings.Default.VS2010_TuitionPayment_Authentication_Authentication;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAuthorizationTokenCompletedEventHandler GetAuthorizationTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/GetAuthorizationToken", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TokenResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public TokenResponse GetAuthorizationToken([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] TokenRequest TokenRequest) {
            object[] results = this.Invoke("GetAuthorizationToken", new object[] {
                        TokenRequest});
            return ((TokenResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizationTokenAsync(TokenRequest TokenRequest) {
            this.GetAuthorizationTokenAsync(TokenRequest, null);
        }
        
        /// <remarks/>
        public void GetAuthorizationTokenAsync(TokenRequest TokenRequest, object userState) {
            if ((this.GetAuthorizationTokenOperationCompleted == null)) {
                this.GetAuthorizationTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationTokenOperationCompleted);
            }
            this.InvokeAsync("GetAuthorizationToken", new object[] {
                        TokenRequest}, this.GetAuthorizationTokenOperationCompleted, userState);
        }
        
        private void OnGetAuthorizationTokenOperationCompleted(object arg) {
            if ((this.GetAuthorizationTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizationTokenCompleted(this, new GetAuthorizationTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericResponse {
        
        private TrxStatus statusField;
        
        private string trxResultField;
        
        private string tokenIdField;
        
        /// <remarks/>
        public TrxStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TrxResult {
            get {
                return this.trxResultField;
            }
            set {
                this.trxResultField = value;
            }
        }
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum TrxStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ErrorSQL,
        
        /// <remarks/>
        ErrorBusinessLogic,
        
        /// <remarks/>
        ErrorWebService,
        
        /// <remarks/>
        ErrorArguments,
        
        /// <remarks/>
        ErrorSecurity,
        
        /// <remarks/>
        ErrorSystem,
        
        /// <remarks/>
        ErrorMultiple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class TokenResponse : GenericResponse {
        
        private int userIdField;
        
        private SecurityStatusType securityTransactionStatusField;
        
        public TokenResponse() {
            this.userIdField = -1;
            this.securityTransactionStatusField = SecurityStatusType.OK;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(SecurityStatusType.OK)]
        public SecurityStatusType SecurityTransactionStatus {
            get {
                return this.securityTransactionStatusField;
            }
            set {
                this.securityTransactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum SecurityStatusType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        FailedPasswordLength,
        
        /// <remarks/>
        FailedPasswordComplex,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class TokenRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private int staffIdField;
        
        private string signatureField;
        
        private bool tokenNeverExpiresField;
        
        private string messageStateField;
        
        public TokenRequest() {
            this.staffIdField = 0;
            this.signatureField = "";
            this.tokenNeverExpiresField = false;
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int StaffId {
            get {
                return this.staffIdField;
            }
            set {
                this.staffIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TokenNeverExpires {
            get {
                return this.tokenNeverExpiresField;
            }
            set {
                this.tokenNeverExpiresField = value;
            }
        }
        
        /// <remarks/>
        public string MessageState {
            get {
                return this.messageStateField;
            }
            set {
                this.messageStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAuthorizationTokenCompletedEventHandler(object sender, GetAuthorizationTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizationTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizationTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TokenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TokenResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591