//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2010_TuitionPayment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kirkcmapi3:8088/cmc.campuslink.webservices.security/Authentication.asmx")]
        public string VS2010_TuitionPayment_Authentication_Authentication {
            get {
                return ((string)(this["VS2010_TuitionPayment_Authentication_Authentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kirkcmapi3:8088/cmc.campuslink.webservices/StudentWebService.asmx")]
        public string VS2010_TuitionPayment_Student_StudentWebService {
            get {
                return ((string)(this["VS2010_TuitionPayment_Student_StudentWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kirkcmapi3:8088/cmc.campuslink.webservices/ActivityWebService.asmx")]
        public string VS2010_TuitionPayment_Activity_ActivityWebService {
            get {
                return ((string)(this["VS2010_TuitionPayment_Activity_ActivityWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kirkcmapi3:8088/cmc.campuslink.webservices/GetListWebService.asmx")]
        public string VS2010_TuitionPayment_GetList_GetListWebService {
            get {
                return ((string)(this["VS2010_TuitionPayment_GetList_GetListWebService"]));
            }
        }
    }
}
