//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace VS2010_TuitionPayment.GetList {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetListWebServiceSoap", Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericRequest))]
    public partial class GetListWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdatableFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemSettingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetListWebService() {
            this.Url = global::VS2010_TuitionPayment.Properties.Settings.Default.VS2010_TuitionPayment_GetList_GetListWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListCompletedEventHandler GetListCompleted;
        
        /// <remarks/>
        public event GetUpdatableFieldsCompletedEventHandler GetUpdatableFieldsCompleted;
        
        /// <remarks/>
        public event GetSystemSettingCompletedEventHandler GetSystemSettingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/GetList", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetListResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public GetListResponse GetList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] GetListRequest GetListRequest) {
            object[] results = this.Invoke("GetList", new object[] {
                        GetListRequest});
            return ((GetListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListAsync(GetListRequest GetListRequest) {
            this.GetListAsync(GetListRequest, null);
        }
        
        /// <remarks/>
        public void GetListAsync(GetListRequest GetListRequest, object userState) {
            if ((this.GetListOperationCompleted == null)) {
                this.GetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOperationCompleted);
            }
            this.InvokeAsync("GetList", new object[] {
                        GetListRequest}, this.GetListOperationCompleted, userState);
        }
        
        private void OnGetListOperationCompleted(object arg) {
            if ((this.GetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCompleted(this, new GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/GetUpdatableFields", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUpdatableFieldsResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public GetUpdatableFieldsResponse GetUpdatableFields([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] GetUpdatableFieldsRequest GetUpdatableFieldsRequest) {
            object[] results = this.Invoke("GetUpdatableFields", new object[] {
                        GetUpdatableFieldsRequest});
            return ((GetUpdatableFieldsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatableFieldsAsync(GetUpdatableFieldsRequest GetUpdatableFieldsRequest) {
            this.GetUpdatableFieldsAsync(GetUpdatableFieldsRequest, null);
        }
        
        /// <remarks/>
        public void GetUpdatableFieldsAsync(GetUpdatableFieldsRequest GetUpdatableFieldsRequest, object userState) {
            if ((this.GetUpdatableFieldsOperationCompleted == null)) {
                this.GetUpdatableFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatableFieldsOperationCompleted);
            }
            this.InvokeAsync("GetUpdatableFields", new object[] {
                        GetUpdatableFieldsRequest}, this.GetUpdatableFieldsOperationCompleted, userState);
        }
        
        private void OnGetUpdatableFieldsOperationCompleted(object arg) {
            if ((this.GetUpdatableFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatableFieldsCompleted(this, new GetUpdatableFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/GetSystemSetting", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSystemSettingResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public GetSystemSettingResponse GetSystemSetting([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] GetSystemSettingRequest GetSystemSettingRequest) {
            object[] results = this.Invoke("GetSystemSetting", new object[] {
                        GetSystemSettingRequest});
            return ((GetSystemSettingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemSettingAsync(GetSystemSettingRequest GetSystemSettingRequest) {
            this.GetSystemSettingAsync(GetSystemSettingRequest, null);
        }
        
        /// <remarks/>
        public void GetSystemSettingAsync(GetSystemSettingRequest GetSystemSettingRequest, object userState) {
            if ((this.GetSystemSettingOperationCompleted == null)) {
                this.GetSystemSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemSettingOperationCompleted);
            }
            this.InvokeAsync("GetSystemSetting", new object[] {
                        GetSystemSettingRequest}, this.GetSystemSettingOperationCompleted, userState);
        }
        
        private void OnGetSystemSettingOperationCompleted(object arg) {
            if ((this.GetSystemSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemSettingCompleted(this, new GetSystemSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSystemSettingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericResponse {
        
        private TrxStatus statusField;
        
        private string trxResultField;
        
        private string tokenIdField;
        
        /// <remarks/>
        public TrxStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TrxResult {
            get {
                return this.trxResultField;
            }
            set {
                this.trxResultField = value;
            }
        }
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum TrxStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ErrorSQL,
        
        /// <remarks/>
        ErrorBusinessLogic,
        
        /// <remarks/>
        ErrorWebService,
        
        /// <remarks/>
        ErrorArguments,
        
        /// <remarks/>
        ErrorSecurity,
        
        /// <remarks/>
        ErrorSystem,
        
        /// <remarks/>
        ErrorMultiple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetSystemSettingResponse : GenericResponse {
        
        private GetSystemSettingOutMsg[] systemSettingsField;
        
        /// <remarks/>
        public GetSystemSettingOutMsg[] SystemSettings {
            get {
                return this.systemSettingsField;
            }
            set {
                this.systemSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetSystemSettingOutMsg : GenericMsg {
        
        private SystemSettingType settingTypeField;
        
        private string systemSettingKeyField;
        
        private string systemSettingValueField;
        
        private string messageResultField;
        
        private MessageStatusType messageStatusField;
        
        private string messageErrorCodeField;
        
        public GetSystemSettingOutMsg() {
            this.messageStatusField = MessageStatusType.OK;
        }
        
        /// <remarks/>
        public SystemSettingType SettingType {
            get {
                return this.settingTypeField;
            }
            set {
                this.settingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SystemSettingKey {
            get {
                return this.systemSettingKeyField;
            }
            set {
                this.systemSettingKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SystemSettingValue {
            get {
                return this.systemSettingValueField;
            }
            set {
                this.systemSettingValueField = value;
            }
        }
        
        /// <remarks/>
        public string MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MessageStatusType.OK)]
        public MessageStatusType MessageStatus {
            get {
                return this.messageStatusField;
            }
            set {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageErrorCode {
            get {
                return this.messageErrorCodeField;
            }
            set {
                this.messageErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum SystemSettingType {
        
        /// <remarks/>
        AuthenticationMode,
        
        /// <remarks/>
        CorporationName,
        
        /// <remarks/>
        CornerstoneIntegrationSetting,
        
        /// <remarks/>
        DatabaseServerName,
        
        /// <remarks/>
        DatabaseName,
        
        /// <remarks/>
        OtherSystemSetting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum MessageStatusType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        FailedValidation,
        
        /// <remarks/>
        FailedExecution,
        
        /// <remarks/>
        FailedAuthorization,
        
        /// <remarks/>
        FailedOther,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSystemSettingOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSimpleOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListFilteredOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListCustomOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSystemSettingInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListFilteredInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListCustomInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSimpleInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericMsg {
        
        private int messageIdField;
        
        private CustomAttributeMsg[] customAttributesField;
        
        private int correlationIdField;
        
        private bool skipSemanticValidationField;
        
        public GenericMsg() {
            this.messageIdField = -1;
            this.correlationIdField = -1;
            this.skipSemanticValidationField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttributeMsg[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SkipSemanticValidation {
            get {
                return this.skipSemanticValidationField;
            }
            set {
                this.skipSemanticValidationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class CustomAttributeMsg {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSimpleOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListFilteredOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListCustomOutMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericOutMsg : GenericMsg {
        
        private string messageResultField;
        
        private MessageStatusType messageStatusField;
        
        private string messageErrorCodeField;
        
        public GenericOutMsg() {
            this.messageStatusField = MessageStatusType.OK;
        }
        
        /// <remarks/>
        public string MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MessageStatusType.OK)]
        public MessageStatusType MessageStatus {
            get {
                return this.messageStatusField;
            }
            set {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageErrorCode {
            get {
                return this.messageErrorCodeField;
            }
            set {
                this.messageErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetUpdatableFieldsOutMsg : GenericOutMsg {
        
        private UpdateTransactionPropertyInfo[] transactionInMsgPropertiesField;
        
        private string transactionNameField;
        
        private string inMsgTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionInMsgProperties")]
        public UpdateTransactionPropertyInfo[] TransactionInMsgProperties {
            get {
                return this.transactionInMsgPropertiesField;
            }
            set {
                this.transactionInMsgPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionName {
            get {
                return this.transactionNameField;
            }
            set {
                this.transactionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InMsgTypeName {
            get {
                return this.inMsgTypeNameField;
            }
            set {
                this.inMsgTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateTransactionPropertyInfo {
        
        private UpdateFieldInfo[] updateFieldsField;
        
        private string propertyNameField;
        
        private string propertyTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateFields")]
        public UpdateFieldInfo[] UpdateFields {
            get {
                return this.updateFieldsField;
            }
            set {
                this.updateFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyTypeName {
            get {
                return this.propertyTypeNameField;
            }
            set {
                this.propertyTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateFieldInfo {
        
        private string fieldNameField;
        
        private string fieldDataTypeField;
        
        private string fieldDescriptionField;
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string FieldDataType {
            get {
                return this.fieldDataTypeField;
            }
            set {
                this.fieldDataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FieldDescription {
            get {
                return this.fieldDescriptionField;
            }
            set {
                this.fieldDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListSimpleOutMsg : GenericOutMsg {
        
        private EntityTypeSimple itemTypeField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        private ListSimpleItemMsg[] itemsField;
        
        /// <remarks/>
        public EntityTypeSimple ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
        
        /// <remarks/>
        public ListSimpleItemMsg[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum EntityTypeSimple {
        
        /// <remarks/>
        AcademicAdvisor,
        
        /// <remarks/>
        ActivityEventStatus,
        
        /// <remarks/>
        ActivityEventType,
        
        /// <remarks/>
        ActivityResult,
        
        /// <remarks/>
        AddressType,
        
        /// <remarks/>
        AdmissionsOfficer,
        
        /// <remarks/>
        Agency,
        
        /// <remarks/>
        AreaOfInterest,
        
        /// <remarks/>
        AreaOfStudyType,
        
        /// <remarks/>
        Bank,
        
        /// <remarks/>
        BillingMethod,
        
        /// <remarks/>
        CIPCode,
        
        /// <remarks/>
        Citizenship,
        
        /// <remarks/>
        CampusGroup,
        
        /// <remarks/>
        CampusModule,
        
        /// <remarks/>
        College,
        
        /// <remarks/>
        Country,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Course,
        
        /// <remarks/>
        Employer,
        
        /// <remarks/>
        EmploymentStatus,
        
        /// <remarks/>
        Ethnicity,
        
        /// <remarks/>
        ExtraCurricular,
        
        /// <remarks/>
        FundSource,
        
        /// <remarks/>
        Gender,
        
        /// <remarks/>
        GradeLetter,
        
        /// <remarks/>
        GradeLevel,
        
        /// <remarks/>
        GradeScale,
        
        /// <remarks/>
        HighSchool,
        
        /// <remarks/>
        LeadCategory,
        
        /// <remarks/>
        LeadSource,
        
        /// <remarks/>
        LeadType,
        
        /// <remarks/>
        LmsVendor,
        
        /// <remarks/>
        Campus,
        
        /// <remarks/>
        MaritalStatus,
        
        /// <remarks/>
        Module,
        
        /// <remarks/>
        Nationality,
        
        /// <remarks/>
        PreviousEducation,
        
        /// <remarks/>
        QuickLeadTemplate,
        
        /// <remarks/>
        Shift,
        
        /// <remarks/>
        StaffGroup,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        SubsidiaryLedgerType,
        
        /// <remarks/>
        Suffix,
        
        /// <remarks/>
        Term,
        
        /// <remarks/>
        Test,
        
        /// <remarks/>
        Title,
        
        /// <remarks/>
        TransactionCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListSimpleItemMsg {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        private bool activeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListFilteredOutMsg : GenericOutMsg {
        
        private EntityTypeFiltered itemTypeField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        private ListFilteredItemMsg[] itemsField;
        
        /// <remarks/>
        public EntityTypeFiltered ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
        
        /// <remarks/>
        public ListFilteredItemMsg[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum EntityTypeFiltered {
        
        /// <remarks/>
        AcademicYear,
        
        /// <remarks/>
        ActivityTemplate,
        
        /// <remarks/>
        Advisor,
        
        /// <remarks/>
        AgencyBranch,
        
        /// <remarks/>
        BankAccount,
        
        /// <remarks/>
        Campus,
        
        /// <remarks/>
        CampusTCC,
        
        /// <remarks/>
        CampusTIN,
        
        /// <remarks/>
        CreditCard,
        
        /// <remarks/>
        EmployerContact,
        
        /// <remarks/>
        EmployerJob,
        
        /// <remarks/>
        EnrolledProgram,
        
        /// <remarks/>
        FinancialAidAward,
        
        /// <remarks/>
        GradeLetter,
        
        /// <remarks/>
        LeadInquiry,
        
        /// <remarks/>
        Program,
        
        /// <remarks/>
        ProgramVersion,
        
        /// <remarks/>
        SchoolStatus,
        
        /// <remarks/>
        StudentAcademicYear,
        
        /// <remarks/>
        StudentAddress,
        
        /// <remarks/>
        StudentBankAccount,
        
        /// <remarks/>
        StudentLeaseHistory,
        
        /// <remarks/>
        StudentSubsidiaryLedger,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListFilteredItemMsg {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        private bool activeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListCustomOutMsg : GenericOutMsg {
        
        private EntityTypeCustom itemTypeField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        private ListCustomItemMsg[] itemsField;
        
        /// <remarks/>
        public EntityTypeCustom ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
        
        /// <remarks/>
        public ListCustomItemMsg[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum EntityTypeCustom {
        
        /// <remarks/>
        AreaOfStudy,
        
        /// <remarks/>
        CashPayment,
        
        /// <remarks/>
        CourseSection,
        
        /// <remarks/>
        DegreeCourse,
        
        /// <remarks/>
        EnrollmentAdvisor,
        
        /// <remarks/>
        LeadEntranceTest,
        
        /// <remarks/>
        PasswordProfile,
        
        /// <remarks/>
        PostalCode,
        
        /// <remarks/>
        ProspectPreviousEducation,
        
        /// <remarks/>
        StartDate,
        
        /// <remarks/>
        Staff,
        
        /// <remarks/>
        Term,
        
        /// <remarks/>
        ClassAttendance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListCustomItemMsg {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        private bool activeField;
        
        private CustomAttributeMsg[] customAttributesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomAttributes")]
        public CustomAttributeMsg[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSystemSettingInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListFilteredInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListCustomInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSimpleInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericInMsg : GenericMsg {
        
        private string messageStateField;
        
        /// <remarks/>
        public string MessageState {
            get {
                return this.messageStateField;
            }
            set {
                this.messageStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetSystemSettingInMsg : GenericInMsg {
        
        private SystemSettingType systemSettingTypeField;
        
        private string systemSettingKeyField;
        
        /// <remarks/>
        public SystemSettingType SystemSettingType {
            get {
                return this.systemSettingTypeField;
            }
            set {
                this.systemSettingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SystemSettingKey {
            get {
                return this.systemSettingKeyField;
            }
            set {
                this.systemSettingKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetUpdatableFieldsInMsg : GenericInMsg {
        
        private string transactionNameField;
        
        /// <remarks/>
        public string TransactionName {
            get {
                return this.transactionNameField;
            }
            set {
                this.transactionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListFilteredInMsg : GenericInMsg {
        
        private EntityTypeFiltered itemTypeField;
        
        private string itemTypeRootField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        public ListFilteredInMsg() {
            this.itemTypeRootField = "";
        }
        
        /// <remarks/>
        public EntityTypeFiltered ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ItemTypeRoot {
            get {
                return this.itemTypeRootField;
            }
            set {
                this.itemTypeRootField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CampusIds")]
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListCustomInMsg : GenericInMsg {
        
        private EntityTypeCustom itemTypeField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        /// <remarks/>
        public EntityTypeCustom ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CampusIds")]
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ListSimpleInMsg : GenericInMsg {
        
        private EntityTypeSimple itemTypeField;
        
        private bool activeOnlyField;
        
        private int[] campusIdsField;
        
        /// <remarks/>
        public EntityTypeSimple ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CampusIds")]
        public int[] CampusIds {
            get {
                return this.campusIdsField;
            }
            set {
                this.campusIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetUpdatableFieldsResponse : GenericResponse {
        
        private GetUpdatableFieldsOutMsg[] updateTransactionsField;
        
        /// <remarks/>
        public GetUpdatableFieldsOutMsg[] UpdateTransactions {
            get {
                return this.updateTransactionsField;
            }
            set {
                this.updateTransactionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetListResponse : GenericResponse {
        
        private ListSimpleOutMsg[] simpleListsField;
        
        private ListFilteredOutMsg[] filteredListsField;
        
        private ListCustomOutMsg[] customListsField;
        
        /// <remarks/>
        public ListSimpleOutMsg[] SimpleLists {
            get {
                return this.simpleListsField;
            }
            set {
                this.simpleListsField = value;
            }
        }
        
        /// <remarks/>
        public ListFilteredOutMsg[] FilteredLists {
            get {
                return this.filteredListsField;
            }
            set {
                this.filteredListsField = value;
            }
        }
        
        /// <remarks/>
        public ListCustomOutMsg[] CustomLists {
            get {
                return this.customListsField;
            }
            set {
                this.customListsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSystemSettingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUpdatableFieldsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericRequest {
        
        private string tokenIdField;
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetSystemSettingRequest : GenericRequest {
        
        private GetSystemSettingInMsg[] systemSettingsField;
        
        /// <remarks/>
        public GetSystemSettingInMsg[] SystemSettings {
            get {
                return this.systemSettingsField;
            }
            set {
                this.systemSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetUpdatableFieldsRequest : GenericRequest {
        
        private GetUpdatableFieldsInMsg[] updateTransactionsField;
        
        /// <remarks/>
        public GetUpdatableFieldsInMsg[] UpdateTransactions {
            get {
                return this.updateTransactionsField;
            }
            set {
                this.updateTransactionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetListRequest : GenericRequest {
        
        private ListSimpleInMsg[] listSimpleInMsgsField;
        
        private ListFilteredInMsg[] listFilteredInMsgsField;
        
        private ListCustomInMsg[] listCustomInMsgsField;
        
        /// <remarks/>
        public ListSimpleInMsg[] ListSimpleInMsgs {
            get {
                return this.listSimpleInMsgsField;
            }
            set {
                this.listSimpleInMsgsField = value;
            }
        }
        
        /// <remarks/>
        public ListFilteredInMsg[] ListFilteredInMsgs {
            get {
                return this.listFilteredInMsgsField;
            }
            set {
                this.listFilteredInMsgsField = value;
            }
        }
        
        /// <remarks/>
        public ListCustomInMsg[] ListCustomInMsgs {
            get {
                return this.listCustomInMsgsField;
            }
            set {
                this.listCustomInMsgsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetListCompletedEventHandler(object sender, GetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUpdatableFieldsCompletedEventHandler(object sender, GetUpdatableFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatableFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatableFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpdatableFieldsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpdatableFieldsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSystemSettingCompletedEventHandler(object sender, GetSystemSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSystemSettingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSystemSettingResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591