//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace VS2010_TuitionPayment.Student {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StudentWebServiceSoap", Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericRequest))]
    public partial class StudentWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback UpdateStudentInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostStudentLeadOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostStudentInquiryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StudentWebService() {
            this.Url = global::VS2010_TuitionPayment.Properties.Settings.Default.VS2010_TuitionPayment_Student_StudentWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateStudentInfoCompletedEventHandler UpdateStudentInfoCompleted;
        
        /// <remarks/>
        public event GetStudentInfoCompletedEventHandler GetStudentInfoCompleted;
        
        /// <remarks/>
        public event PostStudentLeadCompletedEventHandler PostStudentLeadCompleted;
        
        /// <remarks/>
        public event PostStudentInquiryCompletedEventHandler PostStudentInquiryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/UpdateStudentInfo", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateStudentInfoResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public UpdateStudentInfoResponse UpdateStudentInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] UpdateStudentInfoRequest UpdateStudentInfoRequest) {
            object[] results = this.Invoke("UpdateStudentInfo", new object[] {
                        UpdateStudentInfoRequest});
            return ((UpdateStudentInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStudentInfoAsync(UpdateStudentInfoRequest UpdateStudentInfoRequest) {
            this.UpdateStudentInfoAsync(UpdateStudentInfoRequest, null);
        }
        
        /// <remarks/>
        public void UpdateStudentInfoAsync(UpdateStudentInfoRequest UpdateStudentInfoRequest, object userState) {
            if ((this.UpdateStudentInfoOperationCompleted == null)) {
                this.UpdateStudentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStudentInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateStudentInfo", new object[] {
                        UpdateStudentInfoRequest}, this.UpdateStudentInfoOperationCompleted, userState);
        }
        
        private void OnUpdateStudentInfoOperationCompleted(object arg) {
            if ((this.UpdateStudentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStudentInfoCompleted(this, new UpdateStudentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/GetStudentInfo", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStudentInfoResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public GetStudentInfoResponse GetStudentInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] GetStudentInfoRequest GetStudentInfoRequest) {
            object[] results = this.Invoke("GetStudentInfo", new object[] {
                        GetStudentInfoRequest});
            return ((GetStudentInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentInfoAsync(GetStudentInfoRequest GetStudentInfoRequest) {
            this.GetStudentInfoAsync(GetStudentInfoRequest, null);
        }
        
        /// <remarks/>
        public void GetStudentInfoAsync(GetStudentInfoRequest GetStudentInfoRequest, object userState) {
            if ((this.GetStudentInfoOperationCompleted == null)) {
                this.GetStudentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentInfoOperationCompleted);
            }
            this.InvokeAsync("GetStudentInfo", new object[] {
                        GetStudentInfoRequest}, this.GetStudentInfoOperationCompleted, userState);
        }
        
        private void OnGetStudentInfoOperationCompleted(object arg) {
            if ((this.GetStudentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentInfoCompleted(this, new GetStudentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/PostStudentLead", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PostStudentLeadResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public PostStudentLeadResponse PostStudentLead([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] PostStudentLeadRequest PostStudentLeadRequest) {
            object[] results = this.Invoke("PostStudentLead", new object[] {
                        PostStudentLeadRequest});
            return ((PostStudentLeadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostStudentLeadAsync(PostStudentLeadRequest PostStudentLeadRequest) {
            this.PostStudentLeadAsync(PostStudentLeadRequest, null);
        }
        
        /// <remarks/>
        public void PostStudentLeadAsync(PostStudentLeadRequest PostStudentLeadRequest, object userState) {
            if ((this.PostStudentLeadOperationCompleted == null)) {
                this.PostStudentLeadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostStudentLeadOperationCompleted);
            }
            this.InvokeAsync("PostStudentLead", new object[] {
                        PostStudentLeadRequest}, this.PostStudentLeadOperationCompleted, userState);
        }
        
        private void OnPostStudentLeadOperationCompleted(object arg) {
            if ((this.PostStudentLeadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostStudentLeadCompleted(this, new PostStudentLeadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/PostStudentInquiry", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PostStudentInquiryResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public PostStudentInquiryResponse PostStudentInquiry([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] PostStudentInquiryRequest PostStudentInquiryRequest) {
            object[] results = this.Invoke("PostStudentInquiry", new object[] {
                        PostStudentInquiryRequest});
            return ((PostStudentInquiryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostStudentInquiryAsync(PostStudentInquiryRequest PostStudentInquiryRequest) {
            this.PostStudentInquiryAsync(PostStudentInquiryRequest, null);
        }
        
        /// <remarks/>
        public void PostStudentInquiryAsync(PostStudentInquiryRequest PostStudentInquiryRequest, object userState) {
            if ((this.PostStudentInquiryOperationCompleted == null)) {
                this.PostStudentInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostStudentInquiryOperationCompleted);
            }
            this.InvokeAsync("PostStudentInquiry", new object[] {
                        PostStudentInquiryRequest}, this.PostStudentInquiryOperationCompleted, userState);
        }
        
        private void OnPostStudentInquiryOperationCompleted(object arg) {
            if ((this.PostStudentInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostStudentInquiryCompleted(this, new PostStudentInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentInfoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentInfoResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericResponse {
        
        private TrxStatus statusField;
        
        private string trxResultField;
        
        private string tokenIdField;
        
        /// <remarks/>
        public TrxStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TrxResult {
            get {
                return this.trxResultField;
            }
            set {
                this.trxResultField = value;
            }
        }
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum TrxStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ErrorSQL,
        
        /// <remarks/>
        ErrorBusinessLogic,
        
        /// <remarks/>
        ErrorWebService,
        
        /// <remarks/>
        ErrorArguments,
        
        /// <remarks/>
        ErrorSecurity,
        
        /// <remarks/>
        ErrorSystem,
        
        /// <remarks/>
        ErrorMultiple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentInquiryResponse : GenericResponse {
        
        private PostStudentInquiryOutMsg[] postStudentInquirysField;
        
        /// <remarks/>
        public PostStudentInquiryOutMsg[] PostStudentInquirys {
            get {
                return this.postStudentInquirysField;
            }
            set {
                this.postStudentInquirysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentInquiryOutMsg : GenericOutMsg {
        
        private int studentInquiryIdField;
        
        /// <remarks/>
        public int StudentInquiryId {
            get {
                return this.studentInquiryIdField;
            }
            set {
                this.studentInquiryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentOutMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericOutMsg : GenericMsg {
        
        private string messageResultField;
        
        private MessageStatusType messageStatusField;
        
        private string messageErrorCodeField;
        
        public GenericOutMsg() {
            this.messageStatusField = MessageStatusType.OK;
        }
        
        /// <remarks/>
        public string MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MessageStatusType.OK)]
        public MessageStatusType MessageStatus {
            get {
                return this.messageStatusField;
            }
            set {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageErrorCode {
            get {
                return this.messageErrorCodeField;
            }
            set {
                this.messageErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum MessageStatusType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        FailedValidation,
        
        /// <remarks/>
        FailedExecution,
        
        /// <remarks/>
        FailedAuthorization,
        
        /// <remarks/>
        FailedOther,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LeadSourceMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericMsg {
        
        private int messageIdField;
        
        private CustomAttributeMsg[] customAttributesField;
        
        private int correlationIdField;
        
        private bool skipSemanticValidationField;
        
        public GenericMsg() {
            this.messageIdField = -1;
            this.correlationIdField = -1;
            this.skipSemanticValidationField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttributeMsg[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SkipSemanticValidation {
            get {
                return this.skipSemanticValidationField;
            }
            set {
                this.skipSemanticValidationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class CustomAttributeMsg {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LeadSourceMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericInMsg : GenericMsg {
        
        private string messageStateField;
        
        /// <remarks/>
        public string MessageState {
            get {
                return this.messageStateField;
            }
            set {
                this.messageStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentInquiryInMsg : GenericInMsg {
        
        private int studentIdField;
        
        private int campusIdField;
        
        private System.DateTime leadDateField;
        
        private bool currentField;
        
        private int leadTypeIdField;
        
        private LeadSourceInfo[] leadSourceInfoField;
        
        private int origRepIdField;
        
        private int repIdField;
        
        private int[] programIdsField;
        
        private int programGroupIdField;
        
        private string responsePhoneField;
        
        private System.DateTime responseTimeField;
        
        private System.DateTime responseDateField;
        
        private string commentField;
        
        public PostStudentInquiryInMsg() {
            this.leadDateField = new System.DateTime(599266080000000000);
            this.leadTypeIdField = -1;
            this.origRepIdField = -1;
            this.repIdField = -1;
            this.programGroupIdField = -1;
            this.responseTimeField = new System.DateTime(599266080000000000);
            this.responseDateField = new System.DateTime(599266080000000000);
        }
        
        /// <remarks/>
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
        
        /// <remarks/>
        public int CampusId {
            get {
                return this.campusIdField;
            }
            set {
                this.campusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime LeadDate {
            get {
                return this.leadDateField;
            }
            set {
                this.leadDateField = value;
            }
        }
        
        /// <remarks/>
        public bool Current {
            get {
                return this.currentField;
            }
            set {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int LeadTypeId {
            get {
                return this.leadTypeIdField;
            }
            set {
                this.leadTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadSourceInfo")]
        public LeadSourceInfo[] LeadSourceInfo {
            get {
                return this.leadSourceInfoField;
            }
            set {
                this.leadSourceInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OrigRepId {
            get {
                return this.origRepIdField;
            }
            set {
                this.origRepIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int RepId {
            get {
                return this.repIdField;
            }
            set {
                this.repIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgramIds")]
        public int[] ProgramIds {
            get {
                return this.programIdsField;
            }
            set {
                this.programIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int ProgramGroupId {
            get {
                return this.programGroupIdField;
            }
            set {
                this.programGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResponsePhone {
            get {
                return this.responsePhoneField;
            }
            set {
                this.responsePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime ResponseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime ResponseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class LeadSourceInfo {
        
        private int leadSourceIdField;
        
        private int[] leadVendorIdField;
        
        public LeadSourceInfo() {
            this.leadSourceIdField = -1;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int LeadSourceId {
            get {
                return this.leadSourceIdField;
            }
            set {
                this.leadSourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadVendorId")]
        public int[] LeadVendorId {
            get {
                return this.leadVendorIdField;
            }
            set {
                this.leadVendorIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentLeadInMsg : GenericInMsg {
        
        private int studentIdField;
        
        /// <remarks/>
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentLeadInMsg : PostStudentLeadInMsg {
        
        private UpdateField[] updateFieldsField;
        
        private int[] programIdsField;
        
        private int[] extraCurricularIdsField;
        
        private LeadSourceMsg[] leadSourcesField;
        
        private int[] raceIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateFields")]
        public UpdateField[] UpdateFields {
            get {
                return this.updateFieldsField;
            }
            set {
                this.updateFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgramIds")]
        public int[] ProgramIds {
            get {
                return this.programIdsField;
            }
            set {
                this.programIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtraCurricularIds")]
        public int[] ExtraCurricularIds {
            get {
                return this.extraCurricularIdsField;
            }
            set {
                this.extraCurricularIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadSources")]
        public LeadSourceMsg[] LeadSources {
            get {
                return this.leadSourcesField;
            }
            set {
                this.leadSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RaceIds")]
        public int[] RaceIds {
            get {
                return this.raceIdsField;
            }
            set {
                this.raceIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateField {
        
        private string fieldNameField;
        
        private string fieldValueField;
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string FieldValue {
            get {
                return this.fieldValueField;
            }
            set {
                this.fieldValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class LeadSourceMsg : GenericInMsg {
        
        private int leadSourceIdField;
        
        private int[] leadVendorIdsField;
        
        private bool isPrimarySourceField;
        
        public LeadSourceMsg() {
            this.leadSourceIdField = -1;
            this.isPrimarySourceField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int LeadSourceId {
            get {
                return this.leadSourceIdField;
            }
            set {
                this.leadSourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadVendorIds")]
        public int[] LeadVendorIds {
            get {
                return this.leadVendorIdsField;
            }
            set {
                this.leadVendorIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsPrimarySource {
            get {
                return this.isPrimarySourceField;
            }
            set {
                this.isPrimarySourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetStudentInMsg : GenericInMsg {
        
        private int studentIdField;
        
        /// <remarks/>
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class StudentMsg : GenericMsg {
        
        private int studentIdField;
        
        private string sSNField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private decimal pINField;
        
        private string studentNumberField;
        
        private int genderIdField;
        
        private SimpleOption isHispanicField;
        
        private int[] raceIdsField;
        
        private int campusIdField;
        
        private int leadTypeIdField;
        
        private int[] leadSourceIdsField;
        
        private int admissionsOfficerIdField;
        
        private System.DateTime newAdmissionsOfficerEffectiveDateField;
        
        private string addressField;
        
        private string cityField;
        
        private int stateIdField;
        
        private string postalCodeField;
        
        private bool badAddressField;
        
        private int countryIdField;
        
        private int countyIdField;
        
        private string phoneField;
        
        private string workPhoneField;
        
        private string mobileNumberField;
        
        private string workPhoneExtensionField;
        
        private bool badPhoneField;
        
        private int[] programIdsField;
        
        private int[] enrolledProgramIdsField;
        
        private int areaOfInterestIdField;
        
        private int agencyIdField;
        
        private System.DateTime leadDateField;
        
        private string alienRegistrationNumberField;
        
        private string bestTimeToContactField;
        
        private System.DateTime birthDateField;
        
        private int citizenshipIdField;
        
        private bool nonImmigrantStudentField;
        
        private int collegeIdField;
        
        private string commentsField;
        
        private int currentEmployerIdField;
        
        private SimpleOption hasDisabilityField;
        
        private SimpleOption isVeteranField;
        
        private string driversLicenseNumberField;
        
        private int driversLicenseStateIdField;
        
        private string emailField;
        
        private int employmentStatusIdField;
        
        private System.DateTime startDateField;
        
        private int[] extraCurricularIdsField;
        
        private string otherEmailField;
        
        private string nickNameField;
        
        private string otherPhoneField;
        
        private int previousEducationIdField;
        
        private int highSchoolIdField;
        
        private System.DateTime highSchoolDateEnrolledField;
        
        private bool highSchoolGraduateField;
        
        private System.DateTime highSchoolGradDateField;
        
        private string highSchoolGraduationSessionField;
        
        private string highSchoolGraduationYearField;
        
        private System.DateTime highSchoolLastDateAttendedField;
        
        private int highSchoolSizeField;
        
        private byte highSchoolStudentLevelField;
        
        private int highSchoolStudentRankField;
        
        private byte highSchoolTranscriptTypeField;
        
        private string maidenNameField;
        
        private int maritalStatusIdField;
        
        private string middleNameField;
        
        private int nationalityIdField;
        
        private int titleIdField;
        
        private int suffixIdField;
        
        private int shiftIdField;
        
        private bool dataBlockIndicatorField;
        
        private bool storeOldAddressField;
        
        private int oldAddressTypeIdField;
        
        private bool crmSuppressFlagField;
        
        private System.Nullable<decimal> hSAcademicGPAField;
        
        public StudentMsg() {
            this.pINField = ((decimal)(-1.0m));
            this.genderIdField = -1;
            this.isHispanicField = SimpleOption.NotSpecified;
            this.leadTypeIdField = -1;
            this.admissionsOfficerIdField = -1;
            this.newAdmissionsOfficerEffectiveDateField = new System.DateTime(599266080000000000);
            this.stateIdField = -1;
            this.countryIdField = -1;
            this.countyIdField = -1;
            this.areaOfInterestIdField = -1;
            this.agencyIdField = -1;
            this.leadDateField = new System.DateTime(599266080000000000);
            this.birthDateField = new System.DateTime(599266080000000000);
            this.citizenshipIdField = -1;
            this.collegeIdField = -1;
            this.currentEmployerIdField = -1;
            this.hasDisabilityField = SimpleOption.NotSpecified;
            this.isVeteranField = SimpleOption.NotSpecified;
            this.driversLicenseStateIdField = -1;
            this.employmentStatusIdField = -1;
            this.startDateField = new System.DateTime(599266080000000000);
            this.previousEducationIdField = -1;
            this.highSchoolIdField = -1;
            this.highSchoolDateEnrolledField = new System.DateTime(599266080000000000);
            this.highSchoolGradDateField = new System.DateTime(599266080000000000);
            this.highSchoolLastDateAttendedField = new System.DateTime(599266080000000000);
            this.maritalStatusIdField = -1;
            this.nationalityIdField = -1;
            this.titleIdField = -1;
            this.suffixIdField = -1;
            this.shiftIdField = -1;
            this.oldAddressTypeIdField = -1;
        }
        
        /// <remarks/>
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-1.0")]
        public decimal PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        public string StudentNumber {
            get {
                return this.studentNumberField;
            }
            set {
                this.studentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int GenderId {
            get {
                return this.genderIdField;
            }
            set {
                this.genderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(SimpleOption.NotSpecified)]
        public SimpleOption IsHispanic {
            get {
                return this.isHispanicField;
            }
            set {
                this.isHispanicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RaceIds")]
        public int[] RaceIds {
            get {
                return this.raceIdsField;
            }
            set {
                this.raceIdsField = value;
            }
        }
        
        /// <remarks/>
        public int CampusId {
            get {
                return this.campusIdField;
            }
            set {
                this.campusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int LeadTypeId {
            get {
                return this.leadTypeIdField;
            }
            set {
                this.leadTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadSourceIds")]
        public int[] LeadSourceIds {
            get {
                return this.leadSourceIdsField;
            }
            set {
                this.leadSourceIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int AdmissionsOfficerId {
            get {
                return this.admissionsOfficerIdField;
            }
            set {
                this.admissionsOfficerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime NewAdmissionsOfficerEffectiveDate {
            get {
                return this.newAdmissionsOfficerEffectiveDateField;
            }
            set {
                this.newAdmissionsOfficerEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int StateId {
            get {
                return this.stateIdField;
            }
            set {
                this.stateIdField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool BadAddress {
            get {
                return this.badAddressField;
            }
            set {
                this.badAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CountyId {
            get {
                return this.countyIdField;
            }
            set {
                this.countyIdField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneExtension {
            get {
                return this.workPhoneExtensionField;
            }
            set {
                this.workPhoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        public bool BadPhone {
            get {
                return this.badPhoneField;
            }
            set {
                this.badPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgramIds")]
        public int[] ProgramIds {
            get {
                return this.programIdsField;
            }
            set {
                this.programIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnrolledProgramIds")]
        public int[] EnrolledProgramIds {
            get {
                return this.enrolledProgramIdsField;
            }
            set {
                this.enrolledProgramIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int AreaOfInterestId {
            get {
                return this.areaOfInterestIdField;
            }
            set {
                this.areaOfInterestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int AgencyId {
            get {
                return this.agencyIdField;
            }
            set {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime LeadDate {
            get {
                return this.leadDateField;
            }
            set {
                this.leadDateField = value;
            }
        }
        
        /// <remarks/>
        public string AlienRegistrationNumber {
            get {
                return this.alienRegistrationNumberField;
            }
            set {
                this.alienRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string BestTimeToContact {
            get {
                return this.bestTimeToContactField;
            }
            set {
                this.bestTimeToContactField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CitizenshipId {
            get {
                return this.citizenshipIdField;
            }
            set {
                this.citizenshipIdField = value;
            }
        }
        
        /// <remarks/>
        public bool NonImmigrantStudent {
            get {
                return this.nonImmigrantStudentField;
            }
            set {
                this.nonImmigrantStudentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CollegeId {
            get {
                return this.collegeIdField;
            }
            set {
                this.collegeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CurrentEmployerId {
            get {
                return this.currentEmployerIdField;
            }
            set {
                this.currentEmployerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(SimpleOption.NotSpecified)]
        public SimpleOption HasDisability {
            get {
                return this.hasDisabilityField;
            }
            set {
                this.hasDisabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(SimpleOption.NotSpecified)]
        public SimpleOption IsVeteran {
            get {
                return this.isVeteranField;
            }
            set {
                this.isVeteranField = value;
            }
        }
        
        /// <remarks/>
        public string DriversLicenseNumber {
            get {
                return this.driversLicenseNumberField;
            }
            set {
                this.driversLicenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int DriversLicenseStateId {
            get {
                return this.driversLicenseStateIdField;
            }
            set {
                this.driversLicenseStateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EmploymentStatusId {
            get {
                return this.employmentStatusIdField;
            }
            set {
                this.employmentStatusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtraCurricularIds")]
        public int[] ExtraCurricularIds {
            get {
                return this.extraCurricularIdsField;
            }
            set {
                this.extraCurricularIdsField = value;
            }
        }
        
        /// <remarks/>
        public string OtherEmail {
            get {
                return this.otherEmailField;
            }
            set {
                this.otherEmailField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string OtherPhone {
            get {
                return this.otherPhoneField;
            }
            set {
                this.otherPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int PreviousEducationId {
            get {
                return this.previousEducationIdField;
            }
            set {
                this.previousEducationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int HighSchoolId {
            get {
                return this.highSchoolIdField;
            }
            set {
                this.highSchoolIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime HighSchoolDateEnrolled {
            get {
                return this.highSchoolDateEnrolledField;
            }
            set {
                this.highSchoolDateEnrolledField = value;
            }
        }
        
        /// <remarks/>
        public bool HighSchoolGraduate {
            get {
                return this.highSchoolGraduateField;
            }
            set {
                this.highSchoolGraduateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime HighSchoolGradDate {
            get {
                return this.highSchoolGradDateField;
            }
            set {
                this.highSchoolGradDateField = value;
            }
        }
        
        /// <remarks/>
        public string HighSchoolGraduationSession {
            get {
                return this.highSchoolGraduationSessionField;
            }
            set {
                this.highSchoolGraduationSessionField = value;
            }
        }
        
        /// <remarks/>
        public string HighSchoolGraduationYear {
            get {
                return this.highSchoolGraduationYearField;
            }
            set {
                this.highSchoolGraduationYearField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime HighSchoolLastDateAttended {
            get {
                return this.highSchoolLastDateAttendedField;
            }
            set {
                this.highSchoolLastDateAttendedField = value;
            }
        }
        
        /// <remarks/>
        public int HighSchoolSize {
            get {
                return this.highSchoolSizeField;
            }
            set {
                this.highSchoolSizeField = value;
            }
        }
        
        /// <remarks/>
        public byte HighSchoolStudentLevel {
            get {
                return this.highSchoolStudentLevelField;
            }
            set {
                this.highSchoolStudentLevelField = value;
            }
        }
        
        /// <remarks/>
        public int HighSchoolStudentRank {
            get {
                return this.highSchoolStudentRankField;
            }
            set {
                this.highSchoolStudentRankField = value;
            }
        }
        
        /// <remarks/>
        public byte HighSchoolTranscriptType {
            get {
                return this.highSchoolTranscriptTypeField;
            }
            set {
                this.highSchoolTranscriptTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MaidenName {
            get {
                return this.maidenNameField;
            }
            set {
                this.maidenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MaritalStatusId {
            get {
                return this.maritalStatusIdField;
            }
            set {
                this.maritalStatusIdField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int NationalityId {
            get {
                return this.nationalityIdField;
            }
            set {
                this.nationalityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int TitleId {
            get {
                return this.titleIdField;
            }
            set {
                this.titleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int SuffixId {
            get {
                return this.suffixIdField;
            }
            set {
                this.suffixIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int ShiftId {
            get {
                return this.shiftIdField;
            }
            set {
                this.shiftIdField = value;
            }
        }
        
        /// <remarks/>
        public bool DataBlockIndicator {
            get {
                return this.dataBlockIndicatorField;
            }
            set {
                this.dataBlockIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public bool StoreOldAddress {
            get {
                return this.storeOldAddressField;
            }
            set {
                this.storeOldAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OldAddressTypeId {
            get {
                return this.oldAddressTypeIdField;
            }
            set {
                this.oldAddressTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public bool CrmSuppressFlag {
            get {
                return this.crmSuppressFlagField;
            }
            set {
                this.crmSuppressFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> HSAcademicGPA {
            get {
                return this.hSAcademicGPAField;
            }
            set {
                this.hSAcademicGPAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum SimpleOption {
        
        /// <remarks/>
        NotSpecified,
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetStudentOutMsg : StudentMsg {
        
        private int schoolStatusIdField;
        
        private LeadSourceMsg[] leadSourcesField;
        
        private string messageResultField;
        
        private MessageStatusType messageStatusField;
        
        private string messageErrorCodeField;
        
        public GetStudentOutMsg() {
            this.messageStatusField = MessageStatusType.OK;
        }
        
        /// <remarks/>
        public int SchoolStatusId {
            get {
                return this.schoolStatusIdField;
            }
            set {
                this.schoolStatusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LeadSources")]
        public LeadSourceMsg[] LeadSources {
            get {
                return this.leadSourcesField;
            }
            set {
                this.leadSourcesField = value;
            }
        }
        
        /// <remarks/>
        public string MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MessageStatusType.OK)]
        public MessageStatusType MessageStatus {
            get {
                return this.messageStatusField;
            }
            set {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageErrorCode {
            get {
                return this.messageErrorCodeField;
            }
            set {
                this.messageErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentInMsg : StudentMsg {
        
        private string messageStateField;
        
        /// <remarks/>
        public string MessageState {
            get {
                return this.messageStateField;
            }
            set {
                this.messageStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentLeadOutMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentLeadOutMsg : GenericOutMsg {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentLeadOutMsg : PostStudentLeadOutMsg {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentOutMsg : GenericOutMsg {
        
        private int studentIdField;
        
        /// <remarks/>
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentLeadResponse : GenericResponse {
        
        private UpdateStudentLeadOutMsg[] updateStudentLeadsField;
        
        /// <remarks/>
        public UpdateStudentLeadOutMsg[] UpdateStudentLeads {
            get {
                return this.updateStudentLeadsField;
            }
            set {
                this.updateStudentLeadsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetStudentInfoResponse : GenericResponse {
        
        private GetStudentOutMsg[] studentsField;
        
        /// <remarks/>
        public GetStudentOutMsg[] Students {
            get {
                return this.studentsField;
            }
            set {
                this.studentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentInfoResponse : GenericResponse {
        
        private UpdateStudentOutMsg[] studentsField;
        
        /// <remarks/>
        public UpdateStudentOutMsg[] Students {
            get {
                return this.studentsField;
            }
            set {
                this.studentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentInquiryRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostStudentLeadRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStudentInfoRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateStudentInfoRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericRequest {
        
        private string tokenIdField;
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentInquiryRequest : GenericRequest {
        
        private PostStudentInquiryInMsg[] postStudentInquirysField;
        
        /// <remarks/>
        public PostStudentInquiryInMsg[] PostStudentInquirys {
            get {
                return this.postStudentInquirysField;
            }
            set {
                this.postStudentInquirysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostStudentLeadRequest : GenericRequest {
        
        private UpdateStudentLeadInMsg[] updateStudentLeadsField;
        
        /// <remarks/>
        public UpdateStudentLeadInMsg[] UpdateStudentLeads {
            get {
                return this.updateStudentLeadsField;
            }
            set {
                this.updateStudentLeadsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GetStudentInfoRequest : GenericRequest {
        
        private GetStudentInMsg[] studentsField;
        
        /// <remarks/>
        public GetStudentInMsg[] Students {
            get {
                return this.studentsField;
            }
            set {
                this.studentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class UpdateStudentInfoRequest : GenericRequest {
        
        private UpdateStudentInMsg[] studentsField;
        
        /// <remarks/>
        public UpdateStudentInMsg[] Students {
            get {
                return this.studentsField;
            }
            set {
                this.studentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateStudentInfoCompletedEventHandler(object sender, UpdateStudentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateStudentInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateStudentInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStudentInfoCompletedEventHandler(object sender, GetStudentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetStudentInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetStudentInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostStudentLeadCompletedEventHandler(object sender, PostStudentLeadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostStudentLeadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostStudentLeadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostStudentLeadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostStudentLeadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostStudentInquiryCompletedEventHandler(object sender, PostStudentInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostStudentInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostStudentInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostStudentInquiryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostStudentInquiryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591