//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace VS2010_TuitionPayment.Activity {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActivityWebServiceSoap", Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericRequest))]
    public partial class ActivityWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback PostActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostActivityBatchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActivityWebService() {
            this.Url = global::VS2010_TuitionPayment.Properties.Settings.Default.VS2010_TuitionPayment_Activity_ActivityWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostActivityCompletedEventHandler PostActivityCompleted;
        
        /// <remarks/>
        public event PostActivityBatchCompletedEventHandler PostActivityBatchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/PostActivity", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PostActivityResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public PostActivityResponse PostActivity([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] PostActivityRequest PostActivityRequest) {
            object[] results = this.Invoke("PostActivity", new object[] {
                        PostActivityRequest});
            return ((PostActivityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostActivityAsync(PostActivityRequest PostActivityRequest) {
            this.PostActivityAsync(PostActivityRequest, null);
        }
        
        /// <remarks/>
        public void PostActivityAsync(PostActivityRequest PostActivityRequest, object userState) {
            if ((this.PostActivityOperationCompleted == null)) {
                this.PostActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostActivityOperationCompleted);
            }
            this.InvokeAsync("PostActivity", new object[] {
                        PostActivityRequest}, this.PostActivityOperationCompleted, userState);
        }
        
        private void OnPostActivityOperationCompleted(object arg) {
            if ((this.PostActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostActivityCompleted(this, new PostActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.campusmgmt.com/Soa/Foundation/PostActivityBatch", RequestNamespace="http://www.campusmgmt.com/Soa/Foundation/", ResponseNamespace="http://www.campusmgmt.com/Soa/Foundation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PostActivityResponse", Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
        public PostActivityResponse PostActivityBatch([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")] PostActivityRequest PostActivityRequest) {
            object[] results = this.Invoke("PostActivityBatch", new object[] {
                        PostActivityRequest});
            return ((PostActivityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostActivityBatchAsync(PostActivityRequest PostActivityRequest) {
            this.PostActivityBatchAsync(PostActivityRequest, null);
        }
        
        /// <remarks/>
        public void PostActivityBatchAsync(PostActivityRequest PostActivityRequest, object userState) {
            if ((this.PostActivityBatchOperationCompleted == null)) {
                this.PostActivityBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostActivityBatchOperationCompleted);
            }
            this.InvokeAsync("PostActivityBatch", new object[] {
                        PostActivityRequest}, this.PostActivityBatchOperationCompleted, userState);
        }
        
        private void OnPostActivityBatchOperationCompleted(object arg) {
            if ((this.PostActivityBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostActivityBatchCompleted(this, new PostActivityBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostActivityResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericResponse {
        
        private TrxStatus statusField;
        
        private string trxResultField;
        
        private string tokenIdField;
        
        /// <remarks/>
        public TrxStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TrxResult {
            get {
                return this.trxResultField;
            }
            set {
                this.trxResultField = value;
            }
        }
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum TrxStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ErrorSQL,
        
        /// <remarks/>
        ErrorBusinessLogic,
        
        /// <remarks/>
        ErrorWebService,
        
        /// <remarks/>
        ErrorArguments,
        
        /// <remarks/>
        ErrorSecurity,
        
        /// <remarks/>
        ErrorSystem,
        
        /// <remarks/>
        ErrorMultiple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostActivityResponse : GenericResponse {
        
        private AddNewActivityOutMsg[] addNewActivitiesField;
        
        private EditCloseActivityOutMsg[] editCloseActivitiesField;
        
        /// <remarks/>
        public AddNewActivityOutMsg[] AddNewActivities {
            get {
                return this.addNewActivitiesField;
            }
            set {
                this.addNewActivitiesField = value;
            }
        }
        
        /// <remarks/>
        public EditCloseActivityOutMsg[] EditCloseActivities {
            get {
                return this.editCloseActivitiesField;
            }
            set {
                this.editCloseActivitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class AddNewActivityOutMsg : GenericOutMsg {
        
        private int activityIdField;
        
        /// <remarks/>
        public int ActivityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddNewActivityOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EditCloseActivityOutMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericOutMsg : GenericMsg {
        
        private string messageResultField;
        
        private MessageStatusType messageStatusField;
        
        private string messageErrorCodeField;
        
        public GenericOutMsg() {
            this.messageStatusField = MessageStatusType.OK;
        }
        
        /// <remarks/>
        public string MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MessageStatusType.OK)]
        public MessageStatusType MessageStatus {
            get {
                return this.messageStatusField;
            }
            set {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageErrorCode {
            get {
                return this.messageErrorCodeField;
            }
            set {
                this.messageErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum MessageStatusType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        FailedValidation,
        
        /// <remarks/>
        FailedExecution,
        
        /// <remarks/>
        FailedAuthorization,
        
        /// <remarks/>
        FailedOther,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddNewActivityOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EditCloseActivityOutMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EditCloseActivityInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddNewActivityInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericMsg {
        
        private int messageIdField;
        
        private CustomAttributeMsg[] customAttributesField;
        
        private int correlationIdField;
        
        private bool skipSemanticValidationField;
        
        public GenericMsg() {
            this.messageIdField = -1;
            this.correlationIdField = -1;
            this.skipSemanticValidationField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttributeMsg[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SkipSemanticValidation {
            get {
                return this.skipSemanticValidationField;
            }
            set {
                this.skipSemanticValidationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class CustomAttributeMsg {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EditCloseActivityInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddNewActivityInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericInMsg : GenericMsg {
        
        private string messageStateField;
        
        /// <remarks/>
        public string MessageState {
            get {
                return this.messageStateField;
            }
            set {
                this.messageStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EditCloseActivityInMsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddNewActivityInMsg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class ActivityInMsg : GenericInMsg {
        
        private int activityStatusIdField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private int assignedStaffIdField;
        
        private System.DateTime dueDateField;
        
        private string commentsField;
        
        private ActivityPriorityType priorityField;
        
        private string subjectField;
        
        private string emailSubjectField;
        
        private string sourceSystemField;
        
        private bool crmSuppressFlagField;
        
        public ActivityInMsg() {
            this.activityStatusIdField = -1;
            this.startTimeField = new System.DateTime(599266080000000000);
            this.endTimeField = new System.DateTime(599266080000000000);
            this.assignedStaffIdField = -1;
            this.dueDateField = new System.DateTime(599266080000000000);
            this.priorityField = ActivityPriorityType.Undefined;
            this.emailSubjectField = "";
            this.sourceSystemField = "C";
            this.crmSuppressFlagField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int ActivityStatusId {
            get {
                return this.activityStatusIdField;
            }
            set {
                this.activityStatusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int AssignedStaffId {
            get {
                return this.assignedStaffIdField;
            }
            set {
                this.assignedStaffIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ActivityPriorityType.Undefined)]
        public ActivityPriorityType Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string EmailSubject {
            get {
                return this.emailSubjectField;
            }
            set {
                this.emailSubjectField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("C")]
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CrmSuppressFlag {
            get {
                return this.crmSuppressFlagField;
            }
            set {
                this.crmSuppressFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public enum ActivityPriorityType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class EditCloseActivityInMsg : ActivityInMsg {
        
        private int activityIdField;
        
        private int activityResultIdField;
        
        private System.DateTime dateCompletedField;
        
        private int completedByStaffIdField;
        
        private int organizationIdField;
        
        private int organizationContactIdField;
        
        public EditCloseActivityInMsg() {
            this.activityResultIdField = -1;
            this.dateCompletedField = new System.DateTime(599266080000000000);
            this.completedByStaffIdField = -1;
            this.organizationIdField = -1;
            this.organizationContactIdField = -1;
        }
        
        /// <remarks/>
        public int ActivityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int ActivityResultId {
            get {
                return this.activityResultIdField;
            }
            set {
                this.activityResultIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "1900-01-01T00:00:00")]
        public System.DateTime DateCompleted {
            get {
                return this.dateCompletedField;
            }
            set {
                this.dateCompletedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int CompletedByStaffId {
            get {
                return this.completedByStaffIdField;
            }
            set {
                this.completedByStaffIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OrganizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OrganizationContactId {
            get {
                return this.organizationContactIdField;
            }
            set {
                this.organizationContactIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class AddNewActivityInMsg : ActivityInMsg {
        
        private int activityTemplateIdField;
        
        private int studentIdField;
        
        private int enrolledProgramIdField;
        
        private int studentInquiryIdField;
        
        private int employerIdField;
        
        private int employerJobIdField;
        
        private int employerContactIdField;
        
        private int housingStudentLeaseIdField;
        
        private int organizationIdField;
        
        private int organizationContactIdField;
        
        public AddNewActivityInMsg() {
            this.studentIdField = -1;
            this.enrolledProgramIdField = -1;
            this.studentInquiryIdField = -1;
            this.employerIdField = -1;
            this.employerJobIdField = -1;
            this.employerContactIdField = -1;
            this.housingStudentLeaseIdField = -1;
            this.organizationIdField = -1;
            this.organizationContactIdField = -1;
        }
        
        /// <remarks/>
        public int ActivityTemplateId {
            get {
                return this.activityTemplateIdField;
            }
            set {
                this.activityTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EnrolledProgramId {
            get {
                return this.enrolledProgramIdField;
            }
            set {
                this.enrolledProgramIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int StudentInquiryId {
            get {
                return this.studentInquiryIdField;
            }
            set {
                this.studentInquiryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EmployerJobId {
            get {
                return this.employerJobIdField;
            }
            set {
                this.employerJobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EmployerContactId {
            get {
                return this.employerContactIdField;
            }
            set {
                this.employerContactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int HousingStudentLeaseId {
            get {
                return this.housingStudentLeaseIdField;
            }
            set {
                this.housingStudentLeaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OrganizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int OrganizationContactId {
            get {
                return this.organizationContactIdField;
            }
            set {
                this.organizationContactIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class EditCloseActivityOutMsg : GenericOutMsg {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostActivityRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class GenericRequest {
        
        private string tokenIdField;
        
        /// <remarks/>
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")]
    public partial class PostActivityRequest : GenericRequest {
        
        private AddNewActivityInMsg[] addNewActivitiesField;
        
        private EditCloseActivityInMsg[] editCloseActivitiesField;
        
        /// <remarks/>
        public AddNewActivityInMsg[] AddNewActivities {
            get {
                return this.addNewActivitiesField;
            }
            set {
                this.addNewActivitiesField = value;
            }
        }
        
        /// <remarks/>
        public EditCloseActivityInMsg[] EditCloseActivities {
            get {
                return this.editCloseActivitiesField;
            }
            set {
                this.editCloseActivitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.campusmgmt.com/Soa/Foundation/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private object[] headersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public object[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostActivityCompletedEventHandler(object sender, PostActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostActivityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostActivityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostActivityBatchCompletedEventHandler(object sender, PostActivityBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostActivityBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostActivityBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostActivityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostActivityResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591